services:
  backend:
    build:
      context: ./backend
    image: calc-backend:latest
    ports:
      - "4567:4567"
  frontend:
    build:
      context: ./frontend
    image: calc-frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
