---
- name: Deploy Calculator App using Docker Compose
  hosts: local
  vars:
    tag: "{{ image_tag }}"
  tasks:

    - name: Pull nihonium/calc-frontend image
      docker_image:
        name: nihonium/calc-frontend
        tag: "{{ tag }}"
        source: pull
        state: present

    - name: Pull nihonium/calc-backend image
      docker_image:
        name: nihonium/calc-backend
        tag: "{{ tag }}"
        source: pull
        state: present

    - name: Start calc-backend container
      docker_container:
        name: calc-backend
        image: nihonium/calc-backend:{{ tag }}
        state: started
        ports:
          - "4567:4567"

    - name: Start calc-frontend container
      docker_container:
        name: calc-frontend
        image: nihonium/calc-frontend:{{ tag }}
        state: started
        ports:
          - "8000:8000"
        links:
          - calc-backend